### ISSUE TITLE
Como deve ser feito o PR?

### ISSUE THREAD

**Issue by gulybyte** [BrunoFelixDeSousa/todo-api#1]
Prefere que crie uma nova branch? A esta associe uma issue?
Envie tudo em um unico commit, ou varios?
Prefere que o PR seja mesclado na main?

**Comment by BrunoFelixDeSousa** [comment]
Você pode criar um nova branch. Em relação aos commits, pode ser o quanto for necessário.

**Comment by BrunoFelixDeSousa** [comment]
> Prefere que crie uma nova branch? A esta associe uma issue?
> Envie tudo em um unico commit, ou varios?
> Prefere que o PR seja mesclado na main?

Você pode criar um nova branch. Em relação aos commits, pode ser o quanto for necessário.
